### ISSUE TITLE
A few typos on the page

### ISSUE THREAD

**Issue by michelleannesimon** [xuanyilin/SWMM2PEST2.0#7]
Good job, Xuanyi,  SWMM2PEST is easy to  use. I love the video  Here are some suggested edits to the first page:  Please note changes in " ".

Purpose & "Motivatation"
Hydrologists and engineers must manually prepare input files to execute Storm Water Management Model (SWMM) to use and Parameter ESTimation (PEST) "due to the lack of automation." Most of the time and cost are "wasted" when transferring data back and forth and reading files between the two software. Regarding this situation, SWMM2PEST is developed to automate the calibration process of SWMM by integrating the essential modules of PEST.

References
SWMM: https://www.epa.gov/water-research/storm-water-management-model-swmm
PEST: http://www.pesthomepage.org/

"Note that both SWMM 5 and PEST are necessary to run SWMM2PEST.  SWMM2PEST Verions 2.0 was developed for SWMM 5.1.013 and PEST 15."

Caveats
1.	Do not include the parameter with a value of 0 to do the calibration. 0 can be in the calibration range.
2.	The folder path of the input file cannot contain spaces.
3.	Same parameters in SWMM input file and observation file must be in the same unit.
4.	Make sure the observation data format is the" same format as the output file:"  each line in the observation data file should contain date (mm/dd/yyyy), time (hh:mm:ss) and value, e.g. 01/30/2018 06:59:00 0.0001.

**Comment by XuanyiLin** [comment]
Thanks Michelle for the comments. The readme file has been updated.
